# Generated by Django 4.1.2 on 2023-06-28 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0010_auto_20170531_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
